"""Add created_at and updated_at to users table

Revision ID: 0e6a2221a502
Revises: f5c4f35a6afe
Create Date: 2025-04-10 23:16:34.767464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e6a2221a502'
down_revision: Union[str, None] = 'f5c4f35a6afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed incorrect drop operations detected by autogenerate
    # op.drop_index('ix_credit_transactions_id', table_name='credit_transactions')
    # op.drop_table('credit_transactions')
    # op.drop_index('ix_personal_information_id', table_name='personal_information')
    # op.drop_index('ix_personal_information_user_id', table_name='personal_information')
    # op.drop_table('personal_information')
    # op.drop_table('subscriptions')
    # op.drop_index('ix_user_credits_id', table_name='user_credits')
    # op.drop_table('user_credits')
    # op.drop_table('plans')
    # op.drop_index('ix_email_change_requests_user_id', table_name='email_change_requests')
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # Step 1: Add columns allowing NULLs initially
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # Step 2: Update existing rows with a default value (current timestamp)
    op.execute('UPDATE users SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL OR updated_at IS NULL')

    # Step 3: Alter columns to be NOT NULL
    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    # op.drop_index('ix_users_google_id', table_name='users') # Removed incorrect drop index
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True) # Removed incorrect create index
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at') # Downgrade simply drops the columns
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # op.create_index('ix_email_change_requests_user_id', 'email_change_requests', ['user_id'], unique=False) # Removed incorrect create index
    # Removed incorrect create operations from downgrade
    # op.create_table('plans', ...)
    # op.create_table('user_credits', ...)
    # op.create_index('ix_user_credits_id', 'user_credits', ['id'], unique=False)
    # op.create_table('subscriptions', ...)
    # op.create_table('personal_information', ...)
    # op.create_index('ix_personal_information_user_id', 'personal_information', ['user_id'], unique=False)
    # op.create_index('ix_personal_information_id', 'personal_information', ['id'], unique=False)
    # op.create_table('credit_transactions', ...)
    # op.create_index('ix_credit_transactions_id', 'credit_transactions', ['id'], unique=False)
    # ### end Alembic commands ###
