"""add_free_trial_fields_and_rename_used_free_plan_card_table

Revision ID: 0f1a7f1ea92f
Revises: e88cd6688992
Create Date: 2025-05-06 16:50:03.252976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f1a7f1ea92f'
down_revision: Union[str, None] = 'e88cd6688992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Manual Adjustments for renaming used_free_plan_cards to used_trial_card_fingerprints ---
    op.rename_table('used_free_plan_cards', 'used_trial_card_fingerprints')

    op.add_column('used_trial_card_fingerprints', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_used_trial_card_fingerprints_user_id_users',
        'used_trial_card_fingerprints', 'users',
        ['user_id'], ['id']
    )
    op.create_index(op.f('ix_used_trial_card_fingerprints_user_id'), 'used_trial_card_fingerprints', ['user_id'], unique=False)

    op.alter_column('used_trial_card_fingerprints', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # Drop old unique constraint (uq_stripe_card_fingerprint) from the renamed table
    op.drop_constraint('uq_stripe_card_fingerprint', 'used_trial_card_fingerprints', type_='unique')
    
    # Create new unique constraint
    op.create_unique_constraint('uq_trial_card_fingerprint', 'used_trial_card_fingerprints', ['stripe_card_fingerprint'])

    # Drop old indexes from the renamed table (originally on used_free_plan_cards)
    # Note: op.f() is not used here as these are specific old names.
    op.drop_index('ix_used_free_plan_cards_id', table_name='used_trial_card_fingerprints')
    op.drop_index('ix_used_free_plan_cards_stripe_card_fingerprint', table_name='used_trial_card_fingerprints')
    op.drop_index('ix_used_free_plan_cards_stripe_customer_id', table_name='used_trial_card_fingerprints')
    op.drop_index('ix_used_free_plan_cards_stripe_payment_method_id', table_name='used_trial_card_fingerprints')
    op.drop_index('ix_used_free_plan_cards_stripe_subscription_id', table_name='used_trial_card_fingerprints')

    # Create new indexes for used_trial_card_fingerprints as per the model
    op.create_index(op.f('ix_used_trial_card_fingerprints_id'), 'used_trial_card_fingerprints', ['id'], unique=False)
    # user_id index created above
    op.create_index(op.f('ix_used_trial_card_fingerprints_stripe_customer_id'), 'used_trial_card_fingerprints', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_used_trial_card_fingerprints_stripe_subscription_id'), 'used_trial_card_fingerprints', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_trial_card_fingerprint_lookup', 'used_trial_card_fingerprints', ['stripe_card_fingerprint'], unique=False)
    # --- End Manual Adjustments ---

    # Unrelated autogenerated changes (kept as is)
    op.drop_index('ix_personal_information_id', table_name='personal_information', if_exists=True) # Added if_exists for safety
    op.drop_index('ix_personal_information_user_id', table_name='personal_information', if_exists=True) # Added if_exists for safety
    op.drop_table('personal_information')
    
    # Other autogenerated changes (kept as is)
    op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(
        'fk_credit_transactions_user_id_users_explicit',
        'credit_transactions', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'  # Added for consistency
    ) # Explicit name
    op.drop_index('ix_email_change_requests_user_id', table_name='email_change_requests', if_exists=True) # Added if_exists
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.alter_column('user_credits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_credits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    op.create_foreign_key(
        'fk_user_credits_user_id_users_explicit',
        'user_credits', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'  # Added for consistency
    ) # Explicit name
    op.add_column('users', sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('has_consumed_initial_trial', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.drop_index('ix_users_google_id', table_name='users', if_exists=True) # Added if_exists
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_has_consumed_initial_trial'), 'users', ['has_consumed_initial_trial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_has_consumed_initial_trial'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.drop_column('users', 'has_consumed_initial_trial')
    op.drop_column('users', 'account_status')
    op.drop_constraint('fk_user_credits_user_id_users_explicit', 'user_credits', type_='foreignkey') # Reverted to explicit name
    op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_credits', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_credits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.create_index('ix_email_change_requests_user_id', 'email_change_requests', ['user_id'], unique=False)
    op.drop_constraint('fk_credit_transactions_user_id_users_explicit', 'credit_transactions', type_='foreignkey') # Reverted to explicit name
    op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # --- Manual Adjustments for renaming used_trial_card_fingerprints back to used_free_plan_cards ---
    # Drop new indexes from used_trial_card_fingerprints
    op.drop_index('ix_trial_card_fingerprint_lookup', table_name='used_trial_card_fingerprints')
    op.drop_index(op.f('ix_used_trial_card_fingerprints_stripe_subscription_id'), table_name='used_trial_card_fingerprints')
    op.drop_index(op.f('ix_used_trial_card_fingerprints_stripe_customer_id'), table_name='used_trial_card_fingerprints')
    # op.drop_index(op.f('ix_used_trial_card_fingerprints_user_id'), table_name='used_trial_card_fingerprints') # This is dropped with the column
    op.drop_index(op.f('ix_used_trial_card_fingerprints_id'), table_name='used_trial_card_fingerprints')

    # Drop new unique constraint
    op.drop_constraint('uq_trial_card_fingerprint', 'used_trial_card_fingerprints', type_='unique')
    
    # Recreate old unique constraint
    op.create_unique_constraint('uq_stripe_card_fingerprint', 'used_trial_card_fingerprints', ['stripe_card_fingerprint'])
    
    op.alter_column('used_trial_card_fingerprints', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True) # Was nullable before

    op.drop_constraint('fk_used_trial_card_fingerprints_user_id_users', 'used_trial_card_fingerprints', type_='foreignkey')
    op.drop_column('used_trial_card_fingerprints', 'user_id')
    
    op.rename_table('used_trial_card_fingerprints', 'used_free_plan_cards')

    # Recreate old indexes on used_free_plan_cards
    op.create_index('ix_used_free_plan_cards_stripe_subscription_id', 'used_free_plan_cards', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_payment_method_id', 'used_free_plan_cards', ['stripe_payment_method_id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_customer_id', 'used_free_plan_cards', ['stripe_customer_id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_card_fingerprint', 'used_free_plan_cards', ['stripe_card_fingerprint'], unique=False)
    op.create_index('ix_used_free_plan_cards_id', 'used_free_plan_cards', ['id'], unique=False)
    # --- End Manual Adjustments ---

    # Unrelated autogenerated changes (kept as is)
    op.create_table('personal_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_prefix', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('github', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='personal_information_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='personal_information_pkey'),
    sa.UniqueConstraint('user_id', name='personal_information_user_id_key')
    )
    op.create_index('ix_personal_information_user_id', 'personal_information', ['user_id'], unique=False)
    op.create_index('ix_personal_information_id', 'personal_information', ['id'], unique=False)
    # ### end Alembic commands ###
