"""add_created_at_updated_at_to_subscriptions

Revision ID: a573df5bf723
Revises: c317a4c7fcf9
Create Date: 2025-05-08 16:52:44.913977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a573df5bf723'
down_revision: Union[str, None] = 'c317a4c7fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    op.execute('UPDATE subscriptions SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL OR updated_at IS NULL')

    op.alter_column('subscriptions', 'created_at', nullable=False)
    op.alter_column('subscriptions', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
