"""create_processed_stripe_events_table

Revision ID: c317a4c7fcf9
Revises: 0f1a7f1ea92f
Create Date: 2025-05-06 17:34:53.660582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c317a4c7fcf9'
down_revision: Union[str, None] = '0f1a7f1ea92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_processed_stripe_events_stripe_event_id'), 'processed_stripe_events', ['stripe_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_stripe_events_stripe_event_id'), table_name='processed_stripe_events')
    op.drop_table('processed_stripe_events')
    # ### end Alembic commands ###
