"""remove_username_field

Revision ID: e66712ccad45
Revises: 96467313ec96
Create Date: 2025-03-05 00:01:56.029510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'e66712ccad45'
down_revision: Union[str, None] = '96467313ec96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Handle duplicate emails - keep only one user per email (the oldest one)
    # This SQL identifies duplicate emails and deletes all but the one with lowest ID
    op.execute(text("""
        WITH email_duplicates AS (
            SELECT email, MIN(id) as keep_id
            FROM users
            GROUP BY email
            HAVING COUNT(*) > 1
        )
        DELETE FROM users
        WHERE id IN (
            SELECT u.id
            FROM users u
            JOIN email_duplicates ed ON u.email = ed.email
            WHERE u.id != ed.keep_id
        )
    """))
    
    # Step 2: Remove unique constraint on username if it exists
    # Note: We need to be careful with constraint names as they may be autogenerated
    # First check if the constraint exists with the expected name, otherwise use the index
    try:
        op.drop_constraint('uq_users_username', 'users', type_='unique')
    except:
        try:
            op.drop_index('ix_users_username', table_name='users')
        except:
            # If neither approach works, the constraint might have a different name
            # In a real-world scenario, we would inspect the DB to find the exact name
            pass
    
    # Step 3: Remove username column
    op.drop_column('users', 'username')

    # Ensure email column is properly indexed and unique
    # First check if index already exists to avoid errors
    try:
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    except:
        # Index might already exist
        pass


def downgrade() -> None:
    # Add username column back (for rollback if needed)
    op.add_column('users', sa.Column('username', sa.String(50), nullable=True))
    
    # Generate usernames from emails (for existing records)
    op.execute(text("""
        UPDATE users
        SET username = SUBSTRING(email FROM 1 FOR POSITION('@' IN email) - 1)
            || '_' || id
    """))
    
    # Make username not nullable
    op.alter_column('users', 'username', nullable=False)
    
    # Create unique index for username
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
