"""Add used_free_plan_cards table and plan limitation flag

Revision ID: e88cd6688992
Revises: 0e6a2221a502
Create Date: 2025-05-05 18:38:01.643274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e88cd6688992'
down_revision: Union[str, None] = '0e6a2221a502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_free_plan_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_card_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_card_fingerprint', name='uq_stripe_card_fingerprint')
    )
    op.create_index(op.f('ix_used_free_plan_cards_id'), 'used_free_plan_cards', ['id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_card_fingerprint', 'used_free_plan_cards', ['stripe_card_fingerprint'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_customer_id', 'used_free_plan_cards', ['stripe_customer_id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_payment_method_id', 'used_free_plan_cards', ['stripe_payment_method_id'], unique=False)
    op.create_index('ix_used_free_plan_cards_stripe_subscription_id', 'used_free_plan_cards', ['stripe_subscription_id'], unique=False)
    # Removed unrelated drop/create operations detected by autogenerate
    # op.drop_index('ix_personal_information_id', table_name='personal_information')
    # op.drop_index('ix_personal_information_user_id', table_name='personal_information')
    # op.drop_table('personal_information')
    # op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    # op.create_foreign_key(None, 'credit_transactions', 'users', ['user_id'], ['id'])
    # op.drop_index('ix_email_change_requests_user_id', table_name='email_change_requests')
    op.add_column('plans', sa.Column('is_limited_free', sa.Boolean(), server_default='false', nullable=False))
    # Removed unrelated index creations
    # op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    # op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # Removed unrelated alter/drop/create operations
    # op.alter_column('user_credits', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.alter_column('user_credits', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    # op.create_foreign_key(None, 'user_credits', 'users', ['user_id'], ['id'])
    # op.drop_index('ix_users_google_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unrelated index/FK/alter operations
    # op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    # op.drop_constraint(None, 'user_credits', type_='foreignkey')
    # op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # op.alter_column('user_credits', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.alter_column('user_credits', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    # op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_column('plans', 'is_limited_free')
    # Removed unrelated index/FK/table creations
    # op.create_index('ix_email_change_requests_user_id', 'email_change_requests', ['user_id'], unique=False)
    # op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    # op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # op.create_table('personal_information',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('date_of_birth', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    # sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    # sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('phone_prefix', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    # sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    # sa.Column('github', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='personal_information_user_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='personal_information_pkey'),
    # sa.UniqueConstraint('user_id', name='personal_information_user_id_key')
    # )
    # op.create_index('ix_personal_information_user_id', 'personal_information', ['user_id'], unique=False)
    # op.create_index('ix_personal_information_id', 'personal_information', ['id'], unique=False)
    op.drop_index('ix_used_free_plan_cards_stripe_subscription_id', table_name='used_free_plan_cards')
    op.drop_index('ix_used_free_plan_cards_stripe_payment_method_id', table_name='used_free_plan_cards')
    op.drop_index('ix_used_free_plan_cards_stripe_customer_id', table_name='used_free_plan_cards')
    op.drop_index('ix_used_free_plan_cards_stripe_card_fingerprint', table_name='used_free_plan_cards')
    op.drop_index(op.f('ix_used_free_plan_cards_id'), table_name='used_free_plan_cards')
    op.drop_table('used_free_plan_cards')
    # ### end Alembic commands ###
